"""Gameplay configuration for CalSci Dino."""

SCREEN_WIDTH = 128
SCREEN_HEIGHT = 64

AUTO_PLAY = False
RESET_HI_SCORE = False
HI_SCORE_FILE = "/db/dino_hi.dat"

PLAYER_SAFE_ZONE_WIDTH = 32
CACTI_RESPAWN_RATE = 50
GROUND_CACTI_SCROLL_SPEED = 3
PTERODACTY_SPEED = 5
PTERODACTY_RESPAWN_RATE = 255
INCREASE_FPS_EVERY_N_SCORE_POINTS = 256
LIVES_START = 3
LIVES_MAX = 5
SPAWN_NEW_LIVE_MIN_CYCLES = 800
DAY_NIGHT_SWITCH_CYCLES = 1024
TARGET_FPS_START = 23
TARGET_FPS_MAX = 48

SPLASH_WAIT_STEPS = 50
SPLASH_WAIT_MS = 100
